services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Hsdkj3584
      POSTGRES_DB: todolist
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"  # Expose your Ktor app on port 8080
    environment:
      DB_URL: jdbc:postgresql://db:5432/todolist
      DB_USER: postgres
      DB_PASSWORD: Hsdkj3584
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network: