services:
  db:
    image: postgres:15-alpine
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${PORT_DB}:${PORT_DB}"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
    networks:
      - app-network

  app:
    # keep either image: ... or your local build: block
    # image: zaytsevmxm/todolist-backend:${DOCKER_IMAGE_VERSION}
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "${PORT_APP}:${PORT_APP}"
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      PORT_APP: ${PORT_APP}
    volumes:
      - .:/app
    networks:
      - app-network
    command: "sh ./tools/dev.sh"

volumes:
  db-data:

networks:
  app-network: