services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_URL}
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    build:
      context: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DB_URL: ${DB_URL}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - .:/app
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network: